server:
  port: 8443 #任意のポート番号で良い
  ssl:
    enabled: true # sslのセクションがある時点でtrueがデフォルトなので省略可
    key-store: classpath:./keystore.p12
    key-store-password: yourpassword
    key-store-type: PKCS12
    key-alias: localhost
